stages:
- test
- build

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-job:
  stage: build
  image: nimlang/nim:2.0.4
  script:
    - apt-get -y install build-essential
    - nimble build -y
  artifacts:
    paths:
      - "bin/"
